[package]
name = "rshell"
version = "0.1.0"
authors = ["南浦月 <nanpuyue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.80"
tokio = { version = "0.2.11", features = ["macros", "io-util", "stream", "tcp", "dns"] }
tokio-fd = "0.1.0"